### ISSUE TITLE
Image file creation

### ISSUE THREAD

**Issue by peterjriggs** [dhargopala/pico-waveshare-LCD#2]
I am trying to use the image file converter 'img2img565.py' which imports the cv2 module.
I get an error:- ImportError: no module named 'cv2'
Now, the cv2 module must be available, you have it, but where can I get it from?

**Comment by dhargopala** [comment]
cv2 is OpenCV Library, you can install it using `pip install opencv-python`
[Reference](https://pypi.org/project/opencv-python/)
